# Generated by Django 3.1.7 on 2021-03-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='motif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demande.motif', verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='activite',
            field=models.CharField(choices=[('DGE', 'Dir. Générale'), ('DCF', 'Dir. Financière'), ('DRH', 'Dir. RH'), ('DEX', 'Dir. Exploitation'), ('DET', 'Dir. Technique'), ('DCM', 'Dir. Commerciale'), ('SMG', 'Moyens Generaux'), ('FHY', 'fret Hydrocarbure'), ('FSB', 'fret boisson'), ('FHP', 'fret huile de palm'), ('FTC', 'fret conteneurs'), ('FCS', 'fret canne à sucre'), ('FDI', 'fret divers'), ('LEV', 'levage'), ('LOC', 'location de surfaces'), ('SDI', 'services divers'), ('RAV', 'revenus à ventiler'), ('PAF', 'Prestation Accessoir'), ('COL', 'fret Colis lourds')], max_length=255, verbose_name='Code Activité'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='agence',
            field=models.CharField(choices=[('0000', 'Siège'), ('0001', 'Abidjan (agence principale)'), ('0002', 'Bouaflé'), ('0003', 'San-Pedro'), ('0007', 'Bouaké'), ('0008', 'Yamoussoukro'), ('0009', 'Ferké'), ('0010', 'Minautores')], max_length=255, verbose_name='Code Agence'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='analyse',
            field=models.CharField(choices=[('200', 'Batiment et charge locative'), ('210', 'Voyage & deplacement'), ('220', 'Fourniture & consommable de bureau'), ('230', 'Charge personnel'), ('240', 'Quote-part depreciation immo'), ('250', 'Personnel & services exterieur'), ('260', 'Relation exterieur'), ('270', 'Impôt & taxes'), ('280', 'Autres charges directions et service'), ('900', "Recette d'exploitation"), ('910', 'Frais/Opération (frais voyages)'), ('920', 'Papier administratif-CR'), ('930', "Main d'oevre dédiée"), ('940', 'Quote-part amortissement CR et autres'), ('950', 'Entretien & reparation CR'), ('960', 'Frais generaux')], max_length=255, verbose_name='Code Analyse'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='cod_mat_chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demande.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='cod_vehicule',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Code véhicule'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='code_remorque',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Code remorque'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_frais',
            field=models.DateField(blank=True, null=True, verbose_name='Date de frais'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='demande_item',
            field=models.TextField(null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='imat_remorque',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Imat. remorque'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='imat_vehicule',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Imat. véhicule'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nom_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demande',
            name='num_releve',
            field=models.CharField(max_length=255, null=True, verbose_name='Numéro de relevé'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='prix_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
